# ChangeDINO binary change detection config.
#
# This config is dispatched by tools/train.py and tools/test.py to
# projects/changedino/run_changedino.py.

work_dir = 'results/changedino/bcd'

changedino = dict(
    task='bcd',
    changedino_root='projects/changedino/ChangeDINO',
    # ChangeDINO expects: dataroot/dataset/{train,val,test}/A,B,label
    dataroot=r'D:\Projects\change_detection\CD_datasets',
    dataset='CD_mine/11',
    name='ChangeDINO_BCD',
    checkpoint_dir='results/changedino/bcd',
    result_dir='results/changedino/bcd/results',
    vis_path='vis',
    test_phase='test',
    gpu_ids='0',
    batch_size=4,
    val_batch_size=None,
    num_epochs=100,
    num_workers=0,
    lr=5e-4,
    weight_decay=5e-4,
    train_size=512,
    accelerator='gpu',
    devices=1,
    strategy='auto',
    precision=16,
    save_ckpt_mode='state_dict',
    backbone='mobilenetv2',
    fpn='fpn',
    fpn_channels=128,
    deform_groups=4,
    gamma_mode='SE',
    beta_mode='contextgatedconv',
    alpha=0.25,
    gamma=4,
    infer=dict(
        tif1='',
        tif2='',
        out_base_dir='results/changedino/bcd/big_tif',
        checkpoint_dir='results/changedino/bcd/ChangeDINO_BCD/TrainingFiles',
        name='',
        tile_size=512,
        overlap=128,
        batch_size=16,
        gpu_ids='0',
        no_amp=True,
        binarize_mode='logit_diff',
        prob_threshold=0.7,
        logit_threshold=0.5,
        smooth_overlap=False,
        smooth_kernel_size=3,
        remove_holes_area=200000,
        remove_objects_min_size=800,
        fill_all_holes=False,
        min_area_mu=0.1,
        strict_crs=False,
        weights=[],
        epochs='',
        memmap_dir='',
        suppress_green_growth=False,
        exg_delta_thr=0.10,
        exg2_min_thr=0.05,
        no_auto_align_if_size_mismatch=False,
        align_script='',
    ))
